MolSSI/QCEngine

- .travis.yml
- README.md
- devtools/conda-envs/psi.yaml
- devtools/conda-envs/rdkit.yaml
- devtools/conda-envs/torchani.yaml
- qcengine/__init__.py
- qcengine/compute.py
- qcengine/config.py
- qcengine/programs/__init__.py
- qcengine/programs/psi4.py
- qcengine/programs/rdkit.py
- qcengine/programs/torchani.py
- qcengine/testing.py
- qcengine/tests/test_compute.py
- qcengine/tests/test_config.py
- qcengine/tests/test_procedures.py
- qcengine/units.py
- qcengine/util.py
- setup.py
This PR accomplishes the following:
- Adds QCElemental and pydantic as dependancies (requires Py3.6+).
- Converts all units over to QCElemental CODATA2014 units.
- Overhauls the options to have a separate NodeDescriptor area which can effectively match a node name to a preset description. Closes #12.
- Allows individual configuration to be build from a NodeDescriptor to create a on-the-fly JobConfig.
- A JobConfig is alterable with a new `local_options` command. Closes #3.
> Options Overhaul and QCElemental

- qcengine/config.py
- qcengine/programs/psi4.py
- qcengine/tests/test_config.py
Another Config rework. Still playing around with this in regard to dealing with multiple queue managers. Effectively this allows to have a bit more control over the actual job execution and lessens the general node descriptions. This is interoperating with Parsl/Fireworks/Dask/Slurm/Torque/Cobalt a bit better.
> Reworks Config

- devtools/conda-envs/psi.yaml
- devtools/conda-envs/rdkit.yaml
- devtools/conda-envs/torchani.yaml
- devtools/conda-recipe/meta.yaml
- qcengine/cli.py
- qcengine/compute.py
- qcengine/config.py
- qcengine/programs/__init__.py
- qcengine/programs/psi4.py
- qcengine/programs/rdkit.py
- qcengine/programs/torchani.py
- qcengine/stock_mols.py
- qcengine/tests/test_compute.py
- qcengine/tests/test_procedures.py
- qcengine/util.py
- setup.py
This is an overhaul to the QCEngine program to work with the
Pydantic Models which have been/will be added to the QCElemental package.
Right now, the models are all internal and will always return the
flattened dictionary of near-pure Python objects (numpy arrays being an exception).
The emitted objects should have no Pydantic in them, and right now will not
correctly emit in many casses; errors, procedures; if you try. As we continue
the integration of the QCElemental objects into QCA as a whole, we can
revisit this and get it working correctly.
This will need review since it changes a very large swath of code, all of which
had to be changed to get the tests passing.
Depends on molssi/qcelemental#17
> Implement the QCElemental Models into QCEngine

- devtools/conda-envs/psi.yaml
- devtools/conda-envs/rdkit.yaml
- devtools/conda-envs/torchani.yaml
- docs/source/changelog.rst
- qcengine/programs/psi4.py
- qcengine/tests/test_compute.py
- qcengine/util.py
- setup.py
All other codes currently collect stdout by default besides Psi4. Canonicalizes Psi4 in this case.
> Psi4: Ensures output always goes to stdout field

- .travis.yml
- devtools/README.md
- devtools/conda-envs/psi-nightly.yaml
- devtools/conda-envs/psi.yaml
- devtools/travis-ci/before_install.sh
- setup.cfg
- setup.py
* institute caching of conda pkgs for travis
* allow `python setup.py test` to run pytest
* try dftd3 and psi4 pinnings after v1.3 release
> travis caching, setup.py test, updates psi4 travis

- qcengine/programs/psi4.py
- qcengine/programs/tests/test_programs.py
Psi4 internal failures are now handled gracefully. Also does not force `uks` reference when `reference` keyword is present.
> Psi4: Gracefully handle internal failures

- qcengine/programs/dftd3/runner.py
- qcengine/programs/psi4.py
- qcengine/util.py
Moves Psi4 to run from the CLI to prevent possible multiprocessing issues and fixes a small memory leak after thousands of runs.
This does slow down Psi4 by adding a ~0.5 second startup cost.
> Psi4 run from CLI

- qcengine/programs/psi4.py
qcengine not respecting `REFERENCE` in psi4 input for open-shell. for posterity, test script below, but no good reason to inspect it now.
I patched it here, but the greater question is is case something the runners in qcengine need to be careful of or is it something that the qcel model should validate into a uniform case. Certainly one shouldn't mess with the case of keyword _values_, but keyword _names_ are generally uniform wrt case.
```
import pprint
inp = {'driver': 'energy',
'schema_name': 'qcschema_input',
'schema_version': 1,
'keywords': {'DF_SCF_GUESS': 0, 'REFERENCE': 'ROHF', 'SCF_TYPE': 'PK'},
#'keywords': {'DF_SCF_GUESS': 0, 'reference': 'ROHF', 'SCF_TYPE': 'PK'},
'model': {'basis': 'aug-cc-pvqz', 'method': 'scf'},
'molecule': {'atom_labels': [''],
'atomic_numbers': [3], …
```
> fix cased testing of psi4 keywords

- .travis.yml
- qcengine/programs/psi4.py
When psi's `run_json` is smart enough to form proper error structure, this PR lets engine use it, instead of throwing a validation error.
```
except Exception as exc:
json_data["error"] = {
'error_type': type(exc).__name__,
'error_message': ''.join(traceback.format_exception(*sys.exc_info())),
}
json_data["success"] = False
```
New travis bit is b/c psi4 now needs qcng, but don't want both last-tagged-release and dev qcengine around. Even if the import statements could keep things straight, pytest isn't happy about two tests named the same thing.
> process error from psi4

- qcengine/programs/tests/test_dftd3.py
- qcengine/tests/test_procedures.py
- qcengine/util.py
fix psi4 hanging on complex inputs, remove old fn and unneeded xfail
EDIT Any more elegant solution welcomed. But it has to run the below against this psi4 branch https://github.com/psi4/psi4/pull/1351
```
def test_simple_psi4():
import psi4
dimer = psi4.geometry("""
He 2 0 0
--
He -2 0 0
""")
inp = {
'schema_name': 'qcschema_input',
'schema_version': 1,
'molecule': dimer.to_schema(dtype=2),
'driver': 'gradient',
'model': {
'method': 'SCF/cc-pV[D, T]Z',
'basis': '(auto)',
},
'keywords': {
'function_kwargs': {
'bsse_type': 'CP',
'max_nbody': 2,
'return_total_data': True,
},
},
}
pp.pprint(inp)
ret = qcng.compute(inp, "psi4", raise_error=True).dict()
pp.pprint(ret)
assert compare_values(-5.72527135604184, ret["extras"]["qcvars"]["CURRENT ENERGY"], atol=1e-5)
assert …
```
> stdout shenanigans

- qcengine/programs/terachem.py
- qcengine/programs/tests/test_terachem.py
Change to use to_string and keep the bohr unit. Print "bohr" in the first line of the generated xyz file. Skip one test that compare the output json file (fail because I'm using the qcelemental github version to make sure the to_string method is available. The version is newer than the conda-forge qcelemental version, and won't succeed when comparing the provenance)
> TeraChem: Changed the input parser to call qcelemental to_string method with bohr unit

- qcengine/programs/molpro.py
- qcengine/programs/tests/test_molpro.py
- qcengine/programs/tests/test_terachem.py
- qcengine/testing.py
Molpro can now be run by QCEngine and it passes the tests in `test_molpro.py` when QCEngineRecords is present. Except for `ccsd_water_gradient` test because the CCSD energy is missing from the xml file (I'm still working on fixing this).
> Molpro can now be run by QCEngine

- .travis.yml
- devtools/conda-envs/psi-nightly.yaml
- devtools/conda-envs/psi.yaml
- devtools/conda-envs/torchani.yaml
Some Travis build are taking over half an hour due to caching issues. This removes caching and reduces pytorch GPU requirements to observe timings.
> Travis: Removes caching and reduces pytorch overhead

- .travis.yml
- qcengine/programs/__init__.py
- qcengine/programs/molpro.py
- qcengine/programs/tests/test_molpro.py
- qcengine/programs/tests/test_terachem.py
Purposefully only fixed the Molpro test jobs to see if the Terachem ones fail in CI.
> (WIP) get_program: Added check option and fixed Molpro test jobs

- qcengine/programs/molpro.py
- qcengine/testing.py
The `get_version()` function now works. Currently I'm enforcing that any version of Molpro below 2018.1 won't work with QCEngine (the version of Molpro I've been testing these output parsers on). I haven't tested that extensively. Should I comment out that restriction for now?
> Molpro: Implementing get_version for Molpro engine

- qcengine/programs/psi4.py
- qcengine/tests/test_procedures.py
Psi4 natively exports `qcvars` in most version. The redirect is only there for older versions of Psi4, but was causing additional fields to be populated in newer versions of Psi4 with a `None` value. This now correctly assigns `qcvars` in older versions of Psi4 with a decision tree.
Also adds an additional geometric test to ensure keywords are continuously passed through.
> Psi4 QCVars 

- devtools/conda-envs/psi.yaml
- qcengine/programs/base.py
- qcengine/programs/entos.py
- qcengine/programs/tests/test_entos.py
- qcengine/testing.py
I've added entos as an engine. It includes all functions to be run by `qcng.compute()` and the ability to run `entos.build_input()`, `entos.execute()`, and `entos.parse_output()`. I've begun adding support for using Jinja templates so we can cover the different ways might want to provide custom template files. 
(A) ordinary build_input (need to define a base template)
(B) user wants to add stuff after normal template (A)
(C) user knows their domain language (doesn't use any QCSchema quantities)
Right now it only supports option (C). Also right now the output parser does text parsing, but this will be removed eventually since entos plans to output all of their results to a xml or json format.
> Entos: Added entos engine

- docs/source/changelog.rst
Added `__init__.py` file to the `programs/tests` directory so that the
files within will be correctly included in the package.
> Include programs/tests in package bundle

- qcengine/programs/gamess/runner.py
The gradient and molecule parsed from a GAMESS calculation output file are now returned in `parse_output`
> Return GAMESS gradient & molecule in Result

- qcengine/programs/nwchem/harvester.py
Adding back capability of NWChem's harvester to pull TCE options that have been able to in QCDB.
> nwc: tce general cases fix

- qcengine/programs/psi4.py
- qcengine/programs/tests/test_dftd3_mp2d.py
Manages an explicit folder for each Psi4 job to write into and passes the scratch directory via `-s` command line.
Previously the scratch was not correctly set due to a key mismatch in Psi4 `scratch_directory` vs `scratch_location`.
> Psi4 Scratch Control

- docs/source/changelog.rst
- qcengine/compute.py
Something in what I think is a serialization step in one of our Fractal
Queue Adapters causes the function signature to lose its
`kwargonlydefaults` field which makes the function look like a required
kwarg which has no defaults and so cant be called correctly.
> 0.8.2 Docs and bugfix for required kwargs in Fractal's stack

- qcengine/programs/gamess/runner.py
- qcengine/programs/molpro.py
The MolproHarness has been updated to handle DFT and CCSD(T) energies and gradients. The output parser went through a large change to accommodate reading in CCSD and CCSD(T) quantities at the same time. And now it should be easier to expand the output parser to support more methods in the future. 
On my local machine I've checked that this passes with the PR https://github.com/MolSSI/QCEngineRecords/pull/15 for QCEngineRecords, although it might be good to run this through Travis as well.
> Molpro update

- qcengine/programs/dftd3.py
- qcengine/programs/mopac.py
- qcengine/programs/mp2d.py
- qcengine/tests/test_procedures.py
- qcengine/tests/test_standard_suite.py
An assumption in the QCA stack is that we can pass through some metadata in a secret `extras` field. This fixes MOPAC and DFTD3 to conform to this standard and adds standard test suits for these items.
Yes, if choose an extra key name that will be overwritten by the program then so be it. Choose wisely (e.g., `__qcfractal_metadata__`).
> Extras passthrough

- qcengine/programs/nwchem/harvester.py
This PR resolves issue #121, by removing extra import statements from `qcengine/programs/nwchem/harvester.py`.
> Removed imports for numpy and load_hessian from nwchem/harvester.py.

- .azure-pipelines.yml
- azure-pipelines.yml
- devtools/azure_ci_images.md
- devtools/conda-envs/base.yaml
This PR creates an Azure Pipeline which uses a custom Docker image we (MolSSI)
maintain and have exclusive access to through Azure Container Registry.
On this image we can house non-public code which will enable us to test
Engine through integrated CI on these codes securely.
I will say, there are lots of shenanigans and chain of about 20-25 different
commits of trying different things which got squished into this, but I can
confirm it works. Once this is merged in, I will activate it on the
Azure side for Engine itself and we can see it in action.
Right now, the image only contains a static MOPAC binary, but we could expand it
to include packages, or make other images and set up a strategy of different
containers to run through the pipeline. Thanks to Jonathan Moussa (@godotalgorithm) …
> Enable Azure CI with custom images for proprietary code

- qcengine/__main__.py
- qcengine/cli.py
- qcengine/tests/test_cli.py
This PR adds CLI tests with STDIN in a coverage-compatible manner. (`subprocess.check_output` has an undocumented, or at least hard to find, `input` field that avoids `communicate`, which breaks coverage).
This PR also adds a `__main__.py` so that `python -m qcengine` calls the CLI.
This PR fully resolves issue #135.
> Add stdin CLI tests and add entry point with __main__

- qcengine/programs/torchani.py
- qcengine/testing.py
- This PR adds `hessian` driver to `torchani.py`
- I have also changed the minimum requirement for TorchANI version from 0.5 to 0.9. 
In [TorchANI 0.8 release](https://github.com/aiqm/torchani/releases/tag/0.8) we fixed the breaking changes recently introduce in PyTorch, and [TorchANI 0.9](https://github.com/aiqm/torchani/releases/tag/0.9) has all the large files removed. This reduces the size of TorchANI installed with pip to ~57MB. We made it optional for users to download the large files via a `download.sh` script.
> Add Hessian driver to torchani.py

- devtools/conda-envs/psi-nightly.yaml
- devtools/conda-envs/psi.yaml
- qcengine/programs/torchani.py
This PR skips intel-openmp version 2019.5-281, which breaks geometric+psi4. See also ContinuumIO/anaconda-issues#11294.
> Skip broken intel-openmp 2019.5-281

- qcengine/programs/mopac.py
- qcengine/programs/tests/test_programs.py
- qcengine/tests/test_procedures.py
Updates MOPAC to have more sensible quantum-chemistry like keywords by default. Also unsure why changing to a Pulay solver changes the answers in some cases.
As a note, I normally don't advocate for this. However, MOPAC is proving to be quite special. In addition, the `&` keywords extension syntax seems to be broken so we cannot currently support arbitrary keywords.
@muammar
> MOPAC: Error handling and keywords

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- devtools/conda-envs/base.yaml
- devtools/conda-envs/psi-nightly.yaml
- devtools/conda-envs/psi.yaml
- devtools/conda-envs/rdkit.yaml
- devtools/conda-envs/torchani.yaml
- docs/requirements.yml
- docs/source/changelog.rst
- setup.py
This updates the change log to 0.11.0.
Updates the Elemental pins to 0.9 (not yet released), so I don't suspect this will pass or even run until then.
I realized I have the month wrong on 0.10's release, so the link on the GitHub releases page for that release change log needs to be edited. This does not change the release itself, its just the URL link.
> 0.11 Changelog and GitHub Templates

- qcengine/programs/cfour/harvester.py
- qcengine/programs/nwchem/keywords.py
no hurry but no harm merging either
> c4 harvesting and nwc formatting improvements

- qcengine/programs/molpro.py
- qcengine/programs/tests/test_standard_suite_ccsd.py
- qcengine/programs/tests/test_standard_suite_hf.py
- qcengine/programs/tests/test_standard_suite_mp2.py
- qcengine/tests/test_harness_canonical.py
- Added Molpro to some of the standard suite (hf, mp2, ccsd). However, Molpro only works in the hf standard suit right now since, a new keyword to turn off frozen-core will need to implemented for the Molpro Harness to pass the mp2 and ccsd standard suite. I've left those commented out for the time being.
- Added a note in the parse_output function outlining the spherical basis set ordering using in Molpro up to angular momentum i.
> Molpro standard suite

- docs/source/program_overview.rst
- qcengine/programs/entos.py
- qcengine/programs/tests/test_entos.py
- qcengine/testing.py
This PR adds hessian and xtb support to the entos harness. It is a companion to MolSSI/QCEngineRecords#21.
> entos: add hessian and xtb support

- qcengine/compute.py
- qcengine/programs/entos.py
- qcengine/programs/tests/test_entos.py
- qcengine/programs/tests/test_standard_suite_hf.py
- qcengine/programs/util/hessparse.py
- qcengine/testing.py
Added the HF subcommand to the entos harness and performed some general cleanup. 
- Removed soon to be deprecated options in entos
- Added more keywords for the available commands in the entos harness. Keyword names are copied from the https://www.entos.info/manual only applicable to the energy command. Will need more consideration for how to pass keywords to the gradient and hessian drivers.
- Added entos to the standard suite test for HF
> Entos: Added subcommands and more keywords

- qcengine/programs/nwchem/germinate.py
- qcengine/programs/nwchem/harvester.py
- qcengine/programs/nwchem/runner.py
Pulling in the hessian file for NWChem jobs. Clumped in with additional testing on QCDB for properties
Notable points that this PR has either accomplished or will accomplish.
- [x ] Added hessian file to keep when running via NWChem
- [ x] Ready to go
> nwc: add hessian file; minor testing updates

- qcengine/programs/dftd3.py
I'm not able to reproduce #186 easily. And it's true that that error is always user input these days. The variant not available was true in 2016, but those executables should have aged out. I think the `get_version` may even filter them away. So on the basis of the aforementioned hunch, I'm just reclassifying.
> dftd3 variant error

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/Lint.yml
- Makefile
- qcengine/config.py
- qcengine/programs/entos.py
- qcengine/programs/nwchem/germinate.py
- qcengine/programs/nwchem/harvester.py
- qcengine/programs/nwchem/runner.py
- qcengine/programs/qchem.py
- qcengine/programs/tests/test_dftd3_mp2d.py
- qcengine/programs/tests/test_programs.py
- qcengine/programs/tests/test_standard_suite_ccsd(t).py
- qcengine/programs/tests/test_standard_suite_ccsd.py
- qcengine/programs/tests/test_standard_suite_hf.py
- qcengine/programs/tests/test_standard_suite_mp2.py
- qcengine/programs/tests/test_turbomole.py
- qcengine/tests/test_cli.py
- qcengine/tests/test_config.py
- qcengine/tests/test_harness_canonical.py
- qcengine/tests/test_mdi.py
- qcengine/tests/test_procedures.py
- qcengine/tests/test_program_utils.py
- qcengine/tests/test_utils.py
- qcengine/util.py
- setup.py
Updates several GitHub templates to QCArchive standard. Reblackens the code base and fixes the error with black on nwchem files (fmt on/off not paired), this also adds a GHA check for black as well.
> Blacken and GHA Linting

- qcengine/programs/nwchem/germinate.py
NWChem: added "dft" to list of exchange functionals.  If method == "dft" let exchange functional be handled by keywords.  Works with mixed functionals like "xc becke88 lyp".  This doesn't deal with cases like 'dft__xc': 'xc vwn_1_rpa 0.19 lyp 0.81 HFexch 0.20  slater 0.80 becke88 nonlocal 0.72'.
NWChem: added "dft" to list of exchange functionals and let xc option be handled by keywords
> NWCHEM:  added keyword dft to xc_functionals list.  If method == "dft"

- qcengine/programs/psi4.py
- qcengine/util.py
Fixes in conjunction with psi4 ddd. Still needs printing cleared out, after I confirm working.
> psi4 windows version and outfile psiapi mode

- qcengine/programs/nwchem/runner.py
- qcengine/tests/test_config.py
- qcengine/util.py
Fixes bugs with how the total number of ranks and memory size for NWChem are determined when there is more than one core per MPI rank
Minor bug fixes for NWChem when more than core per MPI rank is used
> Minor issues involving >1 core per MPI rank

- qcengine/programs/nwchem/harvester.py
- qcengine/programs/nwchem/runner.py
Bug fix: I did not test with >1 MPI rank for NWChem gradients, and found I needed to have all threads read from the database.
Also changed atom_map to False, as suggested in #205 
[I would call this under the same description as the previous NWC gradients PR]
> Fix for NWChem Gradients with >1 MPI Rank

- qcengine/programs/nwchem/runner.py
- qcengine/tests/test_harness_canonical.py
NWChem does not pass the standard harness tests. This PR adds it to the suite of harnesses being tested to show it fails, and then fixes an issue around "extra" tags being eaten.
Fixed missing extras tags in NWChem harness
> Added NWChem to the canonical harness tests, fixed issues

- .codecov.yml
- .travis.yml
- devtools/conda-envs/nwchem.yaml
closes #211 
try ubuntu's nwchem package, as recc by #211
> CI for NWChem

- README.md
- docs/source/changelog.rst
- qcengine/cli.py
- qcengine/programs/base.py
- qcengine/programs/nwchem/runner.py
- qcengine/programs/psi4.py
~Adapt psi harness to choose psithon or psiapi for `found` and `version` fns. What I'm aiming for is to not require PATH _and_ PYTHONPATH environment edits to run psi4 (which calls qcng which calls psi4) when providing full path to exe.~
If psi4 is found through PATH _or_ PYTHONPATH, this sets the env in qcng to make both psithon and psiapi available.
- does not check if you had PATH pointing to one psi4 installation and PYTHONPATH to another. just don't do that.
- running in psiapi when psi4 in PATH only works for latest ddd branch b/c I had to add `psi --module` to access that importdir.
- result of this is that running tests in ddd no longer requires typing path to `bin/psi4` _and_ having PATH set _and_ having PYTHONPATH set. hoping this will avert lots of questions down the road.
wrt …
> psithon and psiapi

- .travis.yml
- devtools/conda-envs/torchani.yaml
- qcengine/programs/openmm.py
- qcengine/programs/rdkit.py
- qcengine/programs/tests/test_programs.py
- qcengine/tests/test_harness_canonical.py
- qcengine/tests/test_procedures.py
Adds MMFF94 to RDKit, adds tests for other OpenMM FF's, and re-enables TorchANI CI testing.
WARNING! I had implemented #192 backwards in the method/basis combination, this is also fixed here.
Adds MMFF94 to RDKit computational abilities.
> RDKit MMFF94 and CI

- qcengine/mdi_server.py
- qcengine/tests/test_mdi.py
The MDI interface implementation in QCEngine currently only supports the pre-release version of the MDI Library.  This PR updates the interface implementation to accommodate changes that were introduced in the 1.0 version of the MDI Library.  The primary modifications include changes to (1) the way NumPy arrays are handled by the MDI Library and (2) updates to the manner in which node information is communicated.
Add support for MDI Library v1.0.0 release
> Update to support MDI v1.0.0

- devtools/conda-envs/psi.yaml
- docs/source/index.rst
- qcengine/compute.py
- qcengine/procedures/base.py
- qcengine/procedures/berny.py
- qcengine/testing.py
- qcengine/tests/test_procedures.py
- qcengine/tests/test_program_utils.py
Following a discussion with @dgasmith, this PR adds a procedure for the [pyberny](https://github.com/jhrmnn/pyberny) geometry optimizer.
The PR is functional, the following test case runs sucessfully:
```python
import qcelemental as qcel
import qcengine as qcng
mol = qcel.models.Molecule(
geometry=[[0, 0, 0], [0, 1.5, 0], [0, 0, 1.5]], symbols=["O", "H", "H"], connectivity=[[0, 1, 1], [0, 2, 1]]
)
opt_input = {
"keywords": {"program": "mopac"},
"input_specification": {"driver": "gradient", "model": {"method": "PM7"}},
"initial_molecule": mol,
}
opt = qcng.compute_procedure(opt_input, "berny")
print(opt)
```
However, the PR is still a work in progress. The following needs to be resolved before merging, and I would welcome input from the QCEngine maintainers:
Added a new geometry optimizer: …
> add procedure for pyberny geometry optimizer

- qcengine/util.py
execute method returns False if retcode > exit_code
Enable util.execute to return True when the return code > 0. This is useful for Unix utilities such as grep.  
Added optional param 'exit_code' (default 0) to 'execute' function.
> added optional param for execute: exit_code

- qcengine/programs/nwchem/runner.py
The stdout from NWChem contains better debugging information than the stderr.
Improved debugging output from NWChem runner
> Return stdout rather than stderr

- qcengine/programs/nwchem/germinate.py
Make all xc_functionals lower case for NWChem. Otherwise, the muster_function will not detect it as a valid option for DFT calculations
Minor bug fix for NWChem
> Make all XC functionals lowercase

- qcengine/config.py
- qcengine/programs/psi4.py
Updates the API after `py-cpuinfo` was bumped to 6.0.0, resolves #252 
`"brand"` key -> `"brand_raw"`
> Update "brand" to "brand_raw" after py-cpuinfo 6.0.0

- qcengine/programs/empirical_dispersion_resources.py
Added dispersion corrections for pbe0-dh from Bremond et al. DOI: 10.1007/s00214-014-1602-6
> Added pbe0-dh d3zero and d3bj dispersion corrections.

- qcengine/programs/cfour/harvester.py
- qcengine/programs/cfour/runner.py
- qcengine/programs/nwchem/runner.py
- qcengine/programs/psi4.py
- qcengine/programs/tests/standard_suite_contracts.py
- qcengine/programs/tests/standard_suite_ref.py
- qcengine/programs/tests/standard_suite_runner.py
- qcengine/programs/tests/test_standard_suite.py
standard suite support for ccsd gradients and ccsd(t) energies (except fc rohf - only validated for cfour -- psi4 is 10^-6 different). also lccd, lccsd, olccd ref values. also fixed an error handling bug in psiapi mode.
> standard suite expansions

- devtools/conda-envs/torchani.yaml
- qcengine/programs/torchani.py
- qcengine/testing.py
TorchANI now supports ANI2x model as of our latest release ([2.1.1](https://github.com/aiqm/torchani/releases/tag/2.1.1)) 
This PR also fixes #247 
[ANI2x](https://pubs.acs.org/doi/10.1021/acs.jctc.0c00121) model is added as an option in TorchANI interface in QCEngine
> Add TorchANI's ANI2x built-in model

- qcengine/mdi_server.py
- qcengine/programs/dftd3.py
- qcengine/programs/entos.py
- qcengine/programs/molpro.py
- qcengine/programs/openmm.py
- qcengine/programs/psi4.py
- qcengine/programs/qchem.py
- qcengine/programs/qcvar_identities_resources.py
- qcengine/programs/rdkit.py
- qcengine/programs/terachem.py
- qcengine/programs/tests/standard_suite_contracts.py
- qcengine/programs/tests/standard_suite_runner.py
- qcengine/programs/tests/test_qchem.py
- qcengine/programs/tests/test_standard_suite.py
- qcengine/programs/tests/test_xtb.py
- qcengine/programs/torchani.py
- qcengine/programs/xtb.py
- qcengine/testing.py
> improving get_version for Molpro and Q-Chem

- devtools/conda-envs/psi.yaml
- docs/source/changelog.rst
- qcengine/programs/cfour/harvester.py
- qcengine/programs/psi4.py
- qcengine/programs/qcvar_identities_resources.py
- qcengine/programs/tests/standard_suite_contracts.py
- qcengine/programs/tests/standard_suite_ref.py
- setup.py
Add reference data for HF gradients, MP3 energies & gradients, and LCCD gradients. Expand contract machinery for HF, MP2.5, MP3, LCCD. Harvest MP3 from Cfour
Also converted the psi4 (non-nightly) conda-env into a "minimum" testing environment.
> standard suite for HF, MP2.5, MP3, LCCD grad

- qcengine/programs/xtb.py
- qcengine/tests/test_harness_canonical.py
Fixes the XTB harness to ensure any data in extra fields are preserved.
Otherwise, we see the following error when completed XTB tasks are sent to QCFractal.
```
[E 200828 14:44:49 web:1792] Uncaught exception POST /queue_manager (::1)
HTTPServerRequest(protocol='https', host='localhost:7874', method='POST', uri='/queue_manager', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
File "/lus/theta-fs0/projects/CSC249ADCD08/qcarchive/env/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
result = method(*self.path_args, **self.path_kwargs)
File "/lus/theta-fs0/projects/CSC249ADCD08/qcarchive/src/QCFractal/qcfractal/queue/handlers.py", line 285, in post
success, error = self.insert_complete_tasks(self.storage, body.data, self.logger)
File …
```
> Add XTB to the standard suite of harnesses

- docs/source/changelog.rst
- qcengine/programs/torchani.py
Only load/instantiate TorchANI models when one is actually used. Currently, all models get instantiated, even though only one ultimately gets used (and cached) in a `compute` call.
Besides the performance hit, the current implementation also appears to cause frequent issues on networked filesystems due to the many individual file reads required to instantiate the models. For [example](https://github.com/openforcefield/qca-dataset-submission/pull/136#issuecomment-687116908):
```
count : 578
geomeTRIC run_json error:
Traceback (most recent call last):
File "/data/homezvol0/tgokey/.local/miniconda3/envs/qcf/lib/python3.7/site-packages/geometric/run_json.py", line 225, in geometric_run_json
geometric.optimize.Optimize(coords, M, IC, engine, None, params)
File …
```
> Torchani lazy model loading

- docs/source/changelog.rst
- qcengine/programs/psi4.py
Currently, useful error reporting with `psi4` under the `Psi4Harness` can be lost due to a missing `"success"` key on `output_data`. This PR makes attempted access of this key return `False` if not present.
Credit to @dgasmith for pointing this out.
Error messages from `Psi4Harness` no longer swallowed by `KeyError`.
> Psi4 error reporting pre-empted by KeyError

- qcengine/programs/tests/test_turbomole.py
- qcengine/programs/turbomole/harvester.py
- qcengine/programs/turbomole/runner.py
Receiving the paper Draft led me to revisit the TurbomoleHarness. As my own code [pysisyphus](https://github.com/eljost/pysisyphus) also supports QCEngine I noticed a bug. In gradient/Hessian calculations the current_energy wasn't set in the output properties, only the repsective energy derivative was returned ... Now the the runner uses "build_atomicproperties" and "build_out" from qcvar_identities_resources to be more consistent.
Furthermore I added support for Hessian calculations (analytical via aoforce for HF/DFT and numerical via NumForce via ricc2). Corresponding tests are provided. The Harness now also has basic memory management.
Fixed missing current_energy in gradient calculation, added basic memory management and support for Hessian calculations.
> Turbomole energy fix, Hessian, Memory managment

- qcengine/programs/terachem.py
The terachem harness was not working do to the absence of a method filed in 
build_input, so I added the missing line.
> added method field to terachem harness

- devtools/conda-envs/openmm.yaml
- docs/source/programs_molecular_mechanics.rst
- qcengine/programs/openmm.py
- qcengine/programs/tests/test_programs.py
This PR handles the migrations needed to use the `openff-toolkit` package (formerly named `openforcefield`)  which is now available on conda-forge. 
The only real difference between the `openforcefield` package previously used here and the new `openff-toolkit` package is all instances of `import openforcefield.XXX` and `from openforcefield.XXX` are now replaced by `import openff.toolkit.XXX` and `from openff.toolkit.XXX`
Migrate to the conda-forge openff-toolkit package.
> Migrate to the C-F OpenFF Toolkit Package

- qcengine/procedures/nwchem_opt/harvester.py
- qcengine/programs/tests/test_nwchem.py
- qcengine/tests/test_procedures.py
Fixes a bug where we retrieved only the initial geometry if you turn off the line-search option in NWChem's driver.
Bug fix: Was retrieving only the first step in a geometry relaxation
> Be able to work without using NWChem's line search

- docs/source/_templates/layout.html
Adds Google Tag Manager's container for Google Analytics 4 to the layout.html template to propagate through all documentation pages allowing for tracking user data for marketing and communications purposes.
> Adds Google Tag Manager Container to QCEngine Docs for GA4

- qcengine/programs/nwchem/errors.py
- qcengine/programs/nwchem/germinate.py
- qcengine/programs/nwchem/harvester.py
- qcengine/programs/nwchem/runner.py
- qcengine/programs/qcvar_identities_resources.py
- qcengine/programs/tests/test_nwchem.py
Adds a simple error corrector for NWChem: Increase the number of iterations if it fails to converge
Automatically increase the number of iterations when NWChem fails to converge
> Error correction for NWChem computations that fail to converge

- qcengine/config.py
- qcengine/programs/torchani.py
Added config for torchani to use GPU, related to this issue https://github.com/MolSSI/QCEngine/issues/326. 
Now we can use `local_options={'device':'cuda'}` to assign the device: 
```
import qcengine as qcng
import qcelemental as qcel
mol = qcel.models.Molecule.from_data("""
O  0.0  0.000  -0.129
H  0.0 -1.494  1.027
H  0.0  1.494  1.027
""")
inp = qcel.models.AtomicInput(
molecule=mol,
driver="energy",
model={"method": "ani2x"}
)
ret = qcng.compute(inp, "torchani", local_options={'device':'cuda'})
print(ret.return_result)
```
> Allowing torchani to use GPU 

- qcengine/procedures/torsiondrive.py
- qcengine/tests/test_procedures.py
This PR adds support for multi molecule inputs to torsion drives bringing the QCFractal and QCEngine behaviour in sync. 
The torsiondrive procedure can use multiple molecules as input to torsiondrives.
> Multi-Molecule Torsiondrives

- qcengine/programs/nwchem/runner.py
- qcengine/tests/test_procedures.py
Adds the ability for NWChem computations to be restartable.
If NWChem terminates due to walltime it leaves the scratch directory. This commit gives each computation a repeatably-named output directory, so that the QCEngine will restart from that directory if it still exists.
NWChem can restart if QCEngine is killed
> Add in restart capability to NWChem

- docs/source/changelog.rst
- qcengine/config.py
Currently, we observe frequent failure of `cpuinfo` to give brand information when used within Docker containers on Pacific Research Platform. It is unclear why, but making QCEngine tolerant of this information being missing would help in production usage.
QCEngine calls now tolerant of missing `brand_raw` or `brand` info from py-cpuinfo.
> Make QCEngine tolerant of `cpuinfo` failure to populate `brand_raw`, `brand`

- qcengine/config.py
- qcengine/procedures/torsiondrive.py
- qcengine/programs/cfour/runner.py
- qcengine/programs/gamess/runner.py
- qcengine/programs/molpro.py
- qcengine/programs/nwchem/runner.py
- qcengine/programs/turbomole/runner.py
This PR refactors the running of the optimizations for the torsiondrive procedure into a function that can be easily overridden by users who would like to implement a parallel version. This avoids users having to deal with the inner workings of the torsiondrives and can instead focus on the distribution of the optimization tasks. 
The torsiondrive procedure has been refactored to make it easier for users to implement a parallel version via subclassing and overwriting the `_spawn_optimizations` method.
cc @SimonBoothroyd
> Refactor torsiondrive for easy parallel subclass

- qcengine/config.py
- qcengine/programs/cfour/runner.py
- qcengine/programs/gamess/runner.py
- qcengine/programs/molpro.py
- qcengine/programs/nwchem/runner.py
- qcengine/programs/turbomole/runner.py
local `make lint` and the GitHub workflow linting do not pass due to a few files not being correctly formatted or having imports incorrectly sorted. This PR simply lints/resorts imports so these checks pass again.
Linted and ordered imports for a few `runner.py` files.
- [ x] Code base linted
- [ x] Ready to go
> Linted files and updated import ordering so linter passes again

- qcengine/programs/tests/test_canonical_fields.py
Since only tests are affected, retain compatibility with pre/post v0.25
> Fix test after qcel v0.25

- docs/source/environment.rst
- docs/source/index.rst
- qcengine/compute.py
- qcengine/config.py
- qcengine/programs/model.py
- qcengine/programs/tests/test_canonical_config.py
- qcengine/programs/tests/test_canonical_fields.py
- qcengine/tests/test_config.py
- qcengine/util.py
closes #348 
Still waiting on comment re: updating `local_config` -> `task_config` but wanted to provide these updates before I forgot.
Updated docstrings and function annotations for compute and compute_procedure. Renamed kwarg `local_config` -> `task_config` to more clearly express that passed options become a `TaskConfig` argument.
- [x ] Code base linted
- [ x] Ready to go
> Updated docstrings and function annotations for compute and compute_procedure

- qcengine/procedures/nwchem_opt/__init__.py
- qcengine/programs/nwchem/runner.py
- qcengine/programs/tests/test_nwchem.py
Allows restarts to work for single-point NWChem computations, adds tests for that functionality.
As written, the NWCHarness does not write the geometry to the input
file for restart calculations. This is great for Driver computations
because it prevents the computation from restarting from the initial
geometry. However, the geometry is required for single point calculations
(esp Hessian, Gradient) because we use the geometry to determine
how NWChem rotates the coordinate system so that we can adjust
any direction-dependant quantities back to the initial coordinate system.
This change is simple: I add a flag that is set by the "driver" computation
to tell the NWCHarness not to write the geometry for restarts.
For clarity, the NWCOptimizerHarness calls the NWChemHardness
to make input files …
> Allow NWChem to restart single-point computations

- qcengine/programs/tests/test_turbomole.py
- qcengine/programs/turbomole/harvester.py
- qcengine/programs/turbomole/runner.py
Parsing Turbomole Hessian was faulty for bigger molecules. This was found [here](https://github.com/eljost/pysisyphus/issues/173). As the present code in QCEngine is derived from my own project [pysisyphus](https://github.com/eljost/pysisyphus) I want to provide my fix here.
I didn't add test for a big Hessian, but I have a 500 kb Hessian file at hand. If you tell me where I could put this file I could include a proper test. I refrained from including the file inline as a pytest.fixture ...
Fixed Hessian-parsing for bigger molecules >= 60 atoms.
Regarding the linting ... i formatted the files I modified using Black, but there appear to be other "unlinted" files, which I did not modify here: 
```bash
make format
[...]
black qcengine
reformatted qcengine/config.py
reformatted …
```
> Hessian parsing fixes for Turbomole Harness

- qcengine/programs/cfour/harvester.py
- qcengine/programs/nwchem/harvester.py
- qcengine/programs/nwchem/runner.py
- qcengine/programs/tests/test_ghost.py
> gradients with ghost atoms for cfour and nwchem

- qcengine/programs/cfour/germinate.py
- qcengine/programs/cfour/runner.py
- qcengine/programs/tests/test_canonical_fields.py
- qcengine/tests/test_procedures.py
- qcengine/util.py
One test fix and some miscellaneous little improvements. The change to `execute` is the only slightly daring one, I think.
> dir structure in execute and properties in Cfour

- devtools/conda-envs/opt-disp.yaml
- devtools/conda-envs/qcore.yaml
- qcengine/programs/mopac.py
- qcengine/programs/tests/test_programs.py
- qcengine/tests/test_procedures.py
- setup.py
* forgiving the electonic energy key seems ok since it was dropped here https://github.com/openmopac/mopac/commit/d6bdb50bcf74cef84e469097601a4e4944926bee#diff-06ee723679a49e30f3287e5ace72eb84e2e7b0703fb00be2c2de151cfb04e26cL422
* not too sure about other test loosening
EDIT: closes #373
> mopac ci lane. pin to qcel 0.25

- qcengine/programs/tests/standard_suite_contracts.py
- qcengine/programs/tests/standard_suite_ref.py
- qcengine/programs/tests/standard_suite_runner.py
- qcengine/programs/tests/test_standard_suite.py
- qcengine/programs/util/ao_reordering.py
This pairs with https://github.com/psi4/psi4/pull/2633. It doesn't affect QCEngine's general purpose, so I'll plan to mint a v0.24.1 with this when the Psi4 use is finalized.
Adds ref values for df ccsd, ccsd(t), a-ccsd(t), for orbital-optimized mp2, mp2.5, mp3, ccd, ccd(t), a-ccd(t), and for remp2 and oremp2. Existing reference values computed with Psi4's dfocc and occ modules have been updated now that it can converge tighter.
> stdsuite testing remp2, oo, dfcc

- .github/workflows/CI.yml
- qcengine/programs/openmm.py
Hi! This is my first contribution here, let me know if I've done anything wrong!
The OpenFF Toolkit v0.11 includes breaking changes, including enforcing that conformer units are specified with the new OpenFF Units package rather than OpenMM units. This PR updates QCEngine to be compatible with the new version while preserving compatibility with the old versions.
Support OpenFF Toolkit v0.11+
> Support OpenFF Toolkit v0.11+ in openmm.py

- docs/source/changelog.rst
- qcengine/programs/dftd3.py
- qcengine/programs/dftd_ng.py
- qcengine/programs/empirical_dispersion_resources.py
- qcengine/programs/tests/test_canonical_config.py
- qcengine/programs/tests/test_dftd3_mp2d.py
- qcengine/programs/tests/test_dftd4.py
> adapt s-dftd3 harness for psi4

- devtools/conda-envs/adcc.yaml
- devtools/conda-envs/qcore.yaml
* according to https://software.entos.ai/qcore/tutorial/ , entos needs a tbb constraint. that fixes the CI error that was showing up at license check time
* @maxscheurer, I think what was happening with the h5 error in adcc CI (e.g., https://github.com/MolSSI/QCEngine/actions/runs/3847917831/jobs/6555003472) was that psi needs hdf5 1.10, and with c-f higher in channel priority, it was having to grab old h5py 3.3 since c-f switched to 1.12 earlier. Now it's getting 1.10-based hdf5 packages from defaults and adcc itself from c-f instead of adcc channel. Presently adcc 0.15.14 and psi4 1.7.
> fix qcore and adcc CI

- .github/workflows/CI.yml
- devtools/conda-envs/adcc.yaml
- devtools/conda-envs/docs-cf.yaml
- devtools/conda-envs/opt-disp.yaml
- devtools/conda-envs/psi-nightly.yaml
- devtools/conda-envs/psi.yaml
- docs/source/changelog.rst
- docs/source/conf.py
- qcengine/compute.py
- qcengine/config.py
- qcengine/procedures/model.py
- qcengine/programs/model.py
- qcengine/programs/tests/test_qchem.py
- qcengine/testing.py
- qcengine/tests/test_config.py
- qcengine/tests/test_harness_canonical.py
- qcengine/util.py
- setup.py
- versioneer.py
iterating on #412 -- I was going to PR to that, but this PR grew, so better to collect comments here.
> Pydanticv2again

- qcengine/procedures/torsiondrive.py
This PR updates the torsiondrive procedure to use the new `task_config` argument which will stop warnings when running torsiondrives, see #408.
The torsiondrive procedure now uses `task_config` internally.
> update torsiondrive to use task config

- devtools/conda-envs/openmm.yaml
- devtools/conda-envs/qcore.yaml
- devtools/conda-envs/xtb.yaml
- qcengine/programs/psi4.py
- qcengine/tests/test_harness_canonical.py
This PR fixes #407 by adding a valid error message which raises a `RandomError` needed to restart the calculations.
Psi4 tasks are now correctly restarted when there is no valid error message.
> Psi4 random fail restarts 

- devtools/conda-envs/openmm.yaml
- qcengine/procedures/berny.py
- qcengine/tests/test_procedures.py
As explained in #402, `berny` optimizer did not respect the `task_config` options. This PR should fix that.
Fix berny optimizer to respect the task_config options
> FIX: berny should respect the task_config

- qcengine/config.py
- qcengine/programs/tests/test_turbomole.py
- qcengine/programs/turbomole/define.py
- qcengine/programs/turbomole/runner.py
- qcengine/tests/test_procedures.py
This PR incorporates some fixes/additions for the Turbomole runner:
- Pass SCF convergence and SCF max. iterations to `define`
- Correctly enable OMP
- Pass `environment` to `execute`
@loriab I'm actually @maxscheurer but from my corporate GH account 😄
> Some Turbomole fixes

- qcengine/cli.py
- qcengine/config.py
- qcengine/tests/test_procedures.py
This allows for setting the task config (number of nodes, memory, etc) via the CLI and by environment variables.
(I am looking to run more via the CLI than the python interface, for various reasons.)
Task configuration can now be set via CLI and environment variables
> Allow specifying task config via environment and CLI

- qcengine/programs/empirical_dispersion_resources.py
- qcengine/programs/gcp.py
- qcengine/testing.py
For psi4 to run B97-3c and r2SCAN-3c the gCP harness needs an update to the allowed methods (limited to the new 'mctc-gcp'). (https://github.com/psi4/psi4/pull/2842) r2SCAN-3c requires manipulation of additional parameters. `dftd4` has been updated to allow this. The D4 harness update sets the additional defaults. Because the dftd4 toml file does not contain these parameters the D4 harness sets them.
Closes #392 
Adds `b973c` and `r2scan3c` methods to the gcp and dftd4 harness.
> update gCP levels and extend D4 defaults

- qcengine/procedures/optking.py
- qcengine/programs/adcc.py
- qcengine/programs/psi4.py
The existing psi4 detection has worked great when psi4 is in order and conda environments prevail, but #389 and #292 show that if something is set up a little wrong with psi4, then everything devolves into an IndexError with the existing psi4 detection.
This PR improves matters by
* in the complete-the-psithon-psiapi-pair blocks:
* only doing string-safe operations on stdout
* forming clearer error responses
* catching stderr instead of tossing it and parsing stdout anyways
* getting rid of `env` passing. As @Flamefire pointed out, the psi4 module is already in sys.path or which_import wouldn't have worked. unlike #389, code is now passing no env so current env is used (and can provide numpy, etc.). I've tested that there's no need to provide env=os.environ to get current env.
* checking …
> overhaul psi4 detection parsing

- .github/workflows/CI.yml
- docs/source/changelog.rst
publicize my local changelog tracker so ppl can speak up for anything important I'm missing for the next release.
> v0.28 changelog

- docs/source/changelog.rst
- qcengine/programs/psi4.py
psi4 on windows was computing lovely stuff like the below, so clearly the `.split()[-1]` that I removed in #418 was needed. The new check that stdout isn't empty should avert trouble with the split. And stdout is a string in util.popen(), so the strip() should be safe.
```
+#2023-08-17T20:15:44.6106581Z [1m[31mE   pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '-D-a-psi4-psi4-objdir-C-Miniconda3-envs-baseenv-python.exe.D-a-psi4-psi4-objdir-stage-bin-psi4.-version.-1.9a1.dev42'[0m
+#2023-08-17T20:15:44.6107842Z ------------------------------- Captured stdout -------------------------------
+#2023-08-17T20:15:44.6108602Z found (no psithon) exc["proc"].returncode=0 so='D:\\a\\psi4\\psi4\\objdir\\stage\\bin\\psi4\r\n' se=''
+#2023-08-17T20:15:44.6109594Z get_version …
```
> Fix psi4 windows version detection

- docs/source/changelog.rst
- qcengine/config.py
- qcengine/tests/test_config.py
Fixed a minor bug introduced at #400
Expected behavior
```python
>>> os.environ["SCRATCH"] = "/my_scratch"
>>> qcng.get_config(task_config={"scratch_directory": "$SCRATCH"})
<JobConfig ncores=2 memory=2.506 scratch_directory='/my_scratch'>
```
observed behavior
```python
>>> os.environ["SCRATCH"] = "/my_scratch"
>>> qcng.get_config(task_config={"scratch_directory": "$SCRATCH"})
<JobConfig ncores=2 memory=2.506 scratch_directory='$SCRATCH'>
```
> Fix parse_environment task_config

- .github/workflows/CI.yml
- devtools/conda-envs/aimnet2.yaml
- qcengine/programs/aimnet2.py
- qcengine/programs/base.py
- qcengine/programs/tests/test_programs.py
- qcengine/testing.py
- qcengine/tests/test_harness_canonical.py
This PR adds an interface to the new [AIMNET2 models](https://github.com/isayevlab/AIMNet2) via a small utility package [pyaimnet2](https://github.com/jthorton/AIMNet2) which allows access to the models via python.
> Add AIMNET2 harness

- .github/workflows/CI.yml
- .pre-commit-config.yaml
- examples/terachem_pbs.py
- qcengine/procedures/base.py
- qcengine/procedures/berny.py
- qcengine/procedures/nwchem_opt/__init__.py
- qcengine/programs/aimnet2.py
- qcengine/programs/base.py
- qcengine/programs/empirical_dispersion_resources.py
- qcengine/programs/mace.py
- qcengine/programs/model.py
- qcengine/programs/nwchem/runner.py
- qcengine/programs/tests/standard_suite_runner.py
- qcengine/programs/tests/test_ghost.py
- qcengine/programs/turbomole/harvester.py
- qcengine/programs/util/__init__.py
- qcengine/tests/test_procedures.py
- setup.py
- versioneer.py
> Csse pyd2 pull altered qcel and run pre-commit

- devtools/conda-envs/psi-nightly.yaml
- docs/source/dev_program_harness.rst
Markdown style auto-enumeration was used instead of rst
Fix "Adding a New Program Harness" step numbering
> fix auto-enumeration

- .github/workflows/CI.yml
- devtools/conda-envs/disp-win.yaml
- devtools/conda-envs/opt-disp-cf.yaml
- docs/source/changelog.rst
- qcengine/cli.py
- qcengine/compute.py
- qcengine/procedures/berny.py
- qcengine/procedures/geometric.py
- qcengine/procedures/model.py
- qcengine/procedures/optking.py
- qcengine/programs/dftd_ng.py
- qcengine/programs/empirical_dispersion_resources.py
- qcengine/programs/model.py
- qcengine/programs/psi4.py
- qcengine/programs/tests/test_molpro.py
- qcengine/programs/tests/test_programs.py
- qcengine/programs/tests/test_qchem.py
- qcengine/programs/tests/test_terachem.py
- qcengine/programs/xtb.py
- qcengine/testing.py
- qcengine/tests/test_cli.py
- qcengine/tests/test_harness_canonical.py
- qcengine/tests/test_procedures.py
- qcengine/util.py
> Csse layout 550 error

- .github/workflows/CI.yml
- docs/source/changelog.rst
- qcengine/compute.py
- qcengine/procedures/berny.py
- qcengine/procedures/geometric.py
- qcengine/procedures/model.py
- qcengine/procedures/nwchem_opt/__init__.py
- qcengine/procedures/nwchem_opt/harvester.py
- qcengine/procedures/optking.py
- qcengine/procedures/torsiondrive.py
- qcengine/programs/cfour/runner.py
- qcengine/programs/mace.py
- qcengine/programs/molpro.py
- qcengine/programs/mrchem.py
- qcengine/programs/nwchem/germinate.py
- qcengine/programs/nwchem/runner.py
- qcengine/programs/psi4.py
- qcengine/programs/qcore.py
- qcengine/programs/rdkit.py
- qcengine/programs/terachem.py
- qcengine/programs/tests/test_dftd3_mp2d.py
- qcengine/programs/tests/test_dftd4.py
- qcengine/programs/tests/test_programs.py
- qcengine/programs/torchani.py
- qcengine/tests/test_cli.py
- qcengine/tests/test_procedures.py
> Csse layout opt/td

- docs/source/changelog.rst
- qcengine/programs/psi4.py
The psi4 frontend calls `python` which may not be available or not have psi4.
This PR replaces the call with `sys.executable`.
closes #450
> Use sys.executable over explicit call to python

- .github/workflows/CI.yml
- .github/workflows/Lint.yml
- devtools/conda-envs/openmm.yaml
- docs/source/changelog.rst
- qcengine/programs/cfour/keywords.py
- qcengine/programs/tests/test_dftd3_mp2d.py
- qcengine/programs/tests/test_standard_suite_hf.py
closes #447
tested locally that fails w/o edit and passes with.
> cfour basis fixes

- devtools/conda-envs/nwchem-cf.yaml
- devtools/conda-envs/opt-disp-cf.yaml
- docs/source/changelog.rst
- qcengine/procedures/base.py
- qcengine/procedures/qcmanybody.py
- qcengine/programs/adcc.py
- qcengine/programs/cfour/harvester.py
- qcengine/programs/psi4.py
- qcengine/testing.py
- qcengine/tests/test_qcmanybody.py
Bulk of #448 . Adds QCManyBody as a procedure and lets it call QCEngine programs for its inputs. This allows interaction energies or many-body expansions to arbitrary order with none, counterpoise, or VMFC basis set superposition error corrections.
> add plain qcmanybody harness

- .github/workflows/CI.yml
- docs/source/changelog.rst
- qcengine/procedures/berny.py
- qcengine/procedures/optking.py
- qcengine/procedures/torsiondrive.py
- qcengine/programs/cfour/harvester.py
- qcengine/programs/gamess/harvester.py
- qcengine/programs/mace.py
- qcengine/programs/molpro.py
- qcengine/programs/mrchem.py
- qcengine/programs/nwchem/harvester.py
- qcengine/programs/psi4.py
- qcengine/programs/qcore.py
- qcengine/programs/qcvar_identities_resources.py
- qcengine/programs/rdkit.py
- qcengine/programs/terachem.py
- qcengine/programs/tests/test_dftd3_mp2d.py
- qcengine/programs/tests/test_ghost.py
- qcengine/programs/tests/test_programs.py
- qcengine/programs/torchani.py
- qcengine/testing.py
- qcengine/tests/test_mdi.py
- qcengine/tests/test_procedures.py
- setup.py
Closes #462  that was upon next2024 with this upon next2025
See changelog `:pr:462`
> Csse layout reorg rb2025
