MolSSI/QCEngine

README.md
qcengine/compute.py
qcengine/psi_compute.py
qcengine/rdkit_compute.py
qcengine/tests/test_compute.py
qcengine/tests/test_procedures.py
qcengine/util.py
setup.cfg

- Logs stdout and stderr to JSON return, closes #5.
- Moves error return field from `error` to `error_message`.
- Provides choice to fail or not via input, closes #4.

General Cleanup

---

.travis.yml
devtools/conda-envs/torchani.yaml
qcengine/__init__.py
qcengine/compute.py
qcengine/config.py
qcengine/programs/__init__.py
qcengine/programs/psi.py
qcengine/programs/rdkit.py
qcengine/programs/torchani.py
qcengine/tests/addons.py
qcengine/tests/test_compute.py
qcengine/tests/test_procedures.py
qcengine/util.py

This PR does the following:
- Adds the TorchANI computer (still in beta).
- Reworks the stdout/err logging to not require more than `n` characters to overwrite the temporary field names.
- Moves compute to a single folder.
Closes #7.

Adds TorchANI

---

qcengine/compute.py
qcengine/programs/__init__.py
qcengine/programs/psi4.py
qcengine/programs/rdkit.py
qcengine/programs/torchani.py

The model currently in QCEngine requires the coder to add their new Python file and then modify two other locations to enable it.  This PR allows the coder to simply add their new Python file to the proper location and have a similarly named function inside of it and that's it.

Auto populate list of programs

---

devtools/conda-envs/psi.yaml
devtools/conda-envs/rdkit.yaml
devtools/conda-envs/torchani.yaml
devtools/conda-recipe/meta.yaml
docs/source/changelog.rst
setup.py

Just like a can of Spam, whats inside is whats on the tin

Update to 0.5.1

---

qcengine/config.py
qcengine/programs/psi4.py

QCEngine was taking up to 3 seconds to load. This PR refactors this problem out so that we now take ~250ms to load.

Improve load times

---

.travis.yml
qcengine/programs/__init__.py
qcengine/programs/executor.py
qcengine/programs/molpro.py
qcengine/programs/psi4.py
qcengine/programs/tests/test_molpro.py
qcengine/tests/test_compute.py

This pull request contains the start of a Molpro input generator and output parser.

Molpro: Input generator and output parser (WIP)

---

docs/requirements.yml

Moving too fast and forgot to install the theme.

Docs: Pulls QCArchive sphinx theme

---

docs/source/changelog.rst

This should include PRs #38 through #43

Update change log for 0.6.2

---

LICENSE
docs/source/conf.py
docs/source/install.rst
setup.py

Removes myself as the author of this project and reworks it under the community heading of "The QCArchive Development Team"

License update

---

qcengine/programs/__init__.py
qcengine/programs/terachem.py
qcengine/programs/tests/test_terachem.py

@dgasmith Hi Daniel, the Terachem input file generator is added here. I created a pull request but later closed it because I found something to change in the test_compute.py. Sorry for the confusion.
Fang

Terachem input file generator 

---

qcengine/programs/psi4.py

Seems to be some conflicts when multiprocessing on a single node.
@loriab If I understand this correctly this will build a temporary directory in the supplied folder (if not none)?

Psi4: Safer multiprocessing by move Psi temps to scratch

---

docs/source/changelog.rst

GitHub's search magic of `merged:>=2019-03-07` really makes these easier
to compile!

Update change log for 0.6.3

---

qcengine/config.py
qcengine/programs/terachem.py
qcengine/programs/tests/test_terachem.py
qcengine/testing.py

Added test cases for the executor. Tests are skipped if TeraChem environment variable not found.

TeraChem: Added environment variables. QCEngine can now drive terachem 

---

qcengine/programs/terachem.py

Also improved how the last SCF iteration info is extracted to make sure it works for FON and other more complicated calculations than regular SCF.

TeraChem: Improvement of output parser: Parse stdout into Result.

---

README.md
devtools/conda-envs/torchani.yaml
docs/source/community.rst
docs/source/index.rst
docs/source/single_compute.rst
qcengine/programs/__init__.py
qcengine/programs/executor.py
qcengine/programs/molpro.py
qcengine/programs/mp2d.py
qcengine/programs/psi4.py
qcengine/programs/rdkit.py
qcengine/programs/terachem.py
qcengine/programs/tests/test_programs.py
qcengine/programs/torchani.py
qcengine/tests/test_procedures.py
qcengine/tests/test_standard_suite.py
qcengine/util.py

Adds ANI1-x and ANI1-ccx models to torchani.

Torchani Update

---

qcengine/programs/molpro.py
qcengine/programs/tests/test_molpro.py

Added CCSD support to output parsing. However, it looks like the ccsd keys (same as mp2 except with the ccsd label) need to be added to the supported keys. I believe in QCSchema?

Molpro: (WIP) Added CCSD support to output parsing

---

qcengine/__init__.py
qcengine/compute.py
qcengine/exceptions.py
qcengine/procedures/base.py
qcengine/procedures/geometric.py
qcengine/programs/__init__.py
qcengine/programs/dftd3/dashparam.py
qcengine/programs/dftd3/runner.py
qcengine/programs/mp2d.py
qcengine/programs/psi4.py
qcengine/programs/rdkit.py
qcengine/programs/terachem.py
qcengine/programs/tests/test_dftd3.py
qcengine/programs/tests/test_programs.py
qcengine/programs/torchani.py
qcengine/tests/test_program_utils.py
qcengine/tests/test_standard_suite.py
qcengine/util.py

Begins custom exceptions as discussed in #66. This is going to be a somewhat rough process I believe as we have many different categories here and integrating into our current ValueErrors will be interesting. In addition we try to split this into two types of errors:
1) Unknown python exceptions which are handled as we currently have them (traceback + unknown_error type in the JSON return)
2) Known python exceptions where the traceback is omitted and only the known error message is returned.
We also get to simplify the executors somewhat as we can localize issues.
This needs a deep review from @loriab, I am anticipating many small issues/questions here.

Custom Exceptions

---

.codecov.yml
qcengine/programs/cfour/__init__.py
qcengine/programs/cfour/harvester.py
qcengine/programs/cfour/runner.py
qcengine/programs/util/__init__.py
qcengine/programs/util/hessparse.py

* Like GAMESS, this is the execution and parsing sides of the Cfour interface, not the input generation (that's next).
* 35 qcdb cfour test cases pass with it.
* there's still lots o'references to non `qcel.models` `Molecule`s

half a Cfour interface

---

docs/source/changelog.rst
qcengine/programs/cfour/harvester.py
qcengine/programs/cfour/runner.py
qcengine/programs/gamess/runner.py
qcengine/util.py

util.execute improvements

---

qcengine/programs/terachem.py

Since the version numbers of TeraChem development versions are not generated in a standard format, here I change it to use regex to make sure it can always work. 
Also found the DECIMAL expression was added to qcelemental, so I removed my duplicated definition of DECIMAL.

TeraChem: modified how TeraChem version is parsed

---

qcengine/util.py

I know you didn't want this option, but it's handy.

add execute(..., scratch_prefix) for debugging

---

docs/source/changelog.rst

Updated the changelog for Molpro and entos updates

Changelog: Updated changelog for entos and Molpro updates.

---

devtools/conda-envs/psi-nightly.yaml
devtools/conda-envs/psi.yaml
devtools/conda-envs/rdkit.yaml
devtools/conda-envs/torchani.yaml
docs/source/changelog.rst
qcengine/programs/cfour/runner.py
qcengine/programs/dftd3.py
qcengine/programs/entos.py
qcengine/programs/gamess/runner.py
qcengine/programs/molpro.py
qcengine/programs/mp2d.py
qcengine/programs/psi4.py
qcengine/programs/terachem.py
qcengine/programs/tests/test_dftd3_mp2d.py
qcengine/util.py
setup.py

ok use of `extras['local_keywords']`?

dftd3: make dftd3 harness-like

---

qcengine/programs/molpro.py

- Added execute function
- Added ability to provide a template to build_input using stdlib functionality
- Updated input generator to handle symmetry and orientation keywords

MolproHarness Update

---

docs/source/changelog.rst

Updates docs for 0.7.0 release

---

qcengine/programs/terachem.py

Enabled extra files in TeraChem scratch folder to be requested by users, collected after program execution, and recorded in the Result object as extras.

TeraChem: Enable user's request of extra output files.

---

qcengine/procedures/geometric.py
qcengine/programs/tests/test_programs.py
qcengine/testing.py
qcengine/tests/test_procedures.py

Fixes a small bug where geometric retry setting were not correctly propagating through to the base code.

Ensures Geometric will correctly retry gradient evaluations

---

qcengine/compute.py
qcengine/testing.py
qcengine/tests/test_config.py
qcengine/util.py

Adds a environment context manager to catch NumPy style parallelization with Python functions.

Compute: Environments

---

qcengine/programs/molpro.py

import set and tuple form typing in molpro.py

---

qcengine/programs/empirical_dispersion_resources.py
qcengine/programs/nwchem/harvester.py

This PR resolves issue #122 by implementing the changes requested for code formatting in `qcengine/programs/empirical_dispersion_resources.py` and raising a `NotImplementedError` in `qcengine/programs/nwchem/harvester.py`.

Changeset from Issue 122.

---

qcengine/programs/gamess/runner.py

This resolves issue #123 by fixing code formatting and removing a commented line of code in gamess/runner.py.

Fix code formatting and remove comments in gamess/runner.py.

---

devtools/azure_ci_images.md
docs/source/changelog.rst

This is just a change log update, but it should trigger the Azure private CI builds. This is mainly me testing I have it all set up correctly now that the YAML file is in place

Update changelog to test the Azure triggers

---

docs/source/install.rst

Tested that pip and conda both work. Stripped out the from source
install.

 Update the install docs

---

README.md

As on the tin, this tests Azure auto-building and badge status
Bear with me as I do testing on both ends (GitHub and Azure)

Testing Azure Integration - Take 2

---

qcengine/programs/model.py

Finished up issue https://github.com/MolSSI/QCEngine/issues/86 by adding a return type for the base execute function of ProgramHarness.

Model: Addressing issue 86 

---

qcengine/programs/entos.py
qcengine/testing.py
qcengine/tests/test_standard_suite.py

- Updated the output parsing to read the json dictionary produced by entos
- Updated the input file generation

Entos Update

---

qcengine/tests/test_procedures.py

Adds a quick test for optimization protocols. As a note this will not pass until the QCElemental release.
The fact that everything else passes without changes means the transparent nature of these is working well!

Protocols: Optimization test

---

qcengine/programs/qchem.py

Minor bug fix to the qchem harness

qchem: Minor fix to parse_output

---

docs/source/environment.rst
qcengine/config.py
qcengine/programs/nwchem/germinate.py
qcengine/programs/nwchem/harvester.py
qcengine/programs/nwchem/runner.py
qcengine/programs/tests/test_nwchem.py
qcengine/tests/test_config.py

Improves support for NWChem in QCEngine.
Not yet.

Improve support for NWChem

---

.github/workflows/Lint.yml
docs/source/changelog.rst
qcengine/programs/psi4.py

Adds the v0.13.0 changelog and fixes GHA lint action.
N/A

v0.13.0 Changelog

---

qcengine/programs/nwchem/harvester.py

Sorry, I approved faulty code. Actually, all NWChem is broken with "NameError: name 'cc' is not defined". This fixes.
- Fix typo breaking NWChem

fix nwchem

---

qcengine/programs/nwchem/harvester.py

NWChem: added lines to parse dispersion energy

NWChem: Read Dispersion

---

README.md
qcengine/programs/nwchem/runner.py
qcengine/programs/psi4.py

Found some edits that missed the last PR. No merge rush, as I may accumulate changes.
Most notable is I'm going with `psi4 --module`, not `psi4 --pythonpath`

misc psiapi adaptions

---

README.md

aggh, one line, please, markdown

---

devtools/conda-envs/psi-nightly.yaml
devtools/conda-envs/psi.yaml
qcengine/programs/openmm.py
qcengine/programs/tests/test_programs.py
qcengine/programs/tests/test_qchem.py
qcengine/programs/tests/test_terachem.py
qcengine/testing.py
qcengine/tests/test_harness_canonical.py
qcengine/tests/test_procedures.py
qcengine/util.py

Applies method/basis discussion from issue #192 and fixes issues with the value of the energy and the gradient scale.
Moves the OpenMM harness to a canonical forcefield based method/basis language combination.

OpenMM Harness Method/Basis overhaul

---

qcengine/programs/psi4.py
qcengine/programs/tests/test_programs.py
qcengine/testing.py

More informative test selector. Make sure psiapi mode is useable outside DDD

make psi4 harness safe for psiapi file cleaning

---

devtools/conda-envs/README.md
qcengine/programs/psi4.py
qcengine/programs/qchem.py

Nothing urgent -- just some advice. If ppl like the expanded p4/qchem messages, I can roll them out to other harnesses.

add conda-envs readme

---

qcengine/programs/nwchem/harvester.py
qcengine/programs/tests/test_nwchem.py

fixes logic with parsing homo and lumo energies from nwchem output
Fixes the logic when parsing for homo and lumo energies

NWCHEM: Adrian dipole/homo/lumo changes

---

qcengine/programs/qcvar_identities_resources.py
qcengine/programs/tests/test_standard_suite.py

Missed import for sys

---

docs/source/changelog.rst

Added changelog entry for v0.15.0

---

LICENSE
pyproject.toml
qcengine/extras.py
qcengine/mdi_server.py
qcengine/procedures/berny.py
qcengine/programs/cfour/harvester.py
qcengine/programs/gamess/harvester.py
qcengine/programs/openmm.py
qcengine/programs/tests/standard_suite_contracts.py
qcengine/programs/tests/standard_suite_ref.py
qcengine/programs/tests/standard_suite_runner.py
qcengine/programs/tests/test_standard_suite.py
qcengine/programs/tests/test_xtb.py
qcengine/util.py

updating year in LICENSE and expanding target versions for black to include py38 are the only material changes. All the rest is `black` changes from v20.

Update LICENSE, fix #267

---

codemeta.json

* It's nice to collect code author info so we have a chance of finding and addressing each other by name, not GitHub ID, at conferences. [Codemeta](https://codemeta.github.io/) is a way to do this.
* @dgasmith @alenaizan @doaa-altarawy @taylor-a-barnes @loriab @nuwandesilva @dotsdl @awvwgk @zachglick @AlexHeide @jhrmnn @ahurta92 @psi-rking @jygrace @sjrl @ffangliu @vivacebelles @devinamatthews @JonathonMisiewicz @Lnaden @jeffschriber @CDSherrill @eljost @WardLT @mattwelborn @twindus, you have been identified as a substantial code author or otherwise contributor to QCEngine or to QCDB code that migrated here.
* @jygrace @sjrl @dotsdl @eljost @ahurta92 @jhrmnn @ffangliu @taylor-a-barnes, I don't have email addresses for you.
* EDIT: If you're not in this file and you think you should be, …

add project authors file

---

qcengine/procedures/base.py
qcengine/procedures/nwchem_opt/__init__.py
qcengine/procedures/nwchem_opt/harvester.py
qcengine/programs/nwchem/harvester.py
qcengine/programs/nwchem/keywords.py
qcengine/tests/test_procedures.py

Adds a harness that uses NWChem's built-in geometry optimizer
My hope is that this will be faster on HPC when my time to launch an NWChem run is significant.
Adds a harness for geometry optimization with NWChem

Harness for using NWChem's relaxation engine

---

qcengine/programs/tests/test_xtb.py

will this be ok, @awvwgk? it fixes CI.

slightly loosen xtb testing

---

qcengine/programs/openmm.py

fix openmm version

---

.github/workflows/CI.yml
devtools/conda-envs/docs-cf.yaml

switch docs to ghpages

---

qcengine/programs/openmm.py

Fixed OpenMMHarness imports to support version 7.6+

---

docs/requirements.yml
docs/source/dev_program_harness.rst
docs/source/index.rst
docs/source/single_compute.rst

a few harness docs

---

devtools/conda-envs/adcc.yaml
devtools/conda-envs/mrchem.yaml
devtools/conda-envs/nwchem.yaml
devtools/conda-envs/opt-disp.yaml
devtools/conda-envs/psi-nightly.yaml
devtools/conda-envs/psi.yaml
devtools/conda-envs/qcore.yaml
docs/source/changelog.rst
qcengine/programs/cfour/harvester.py
qcengine/programs/cfour/runner.py
qcengine/programs/gamess/harvester.py
qcengine/programs/gamess/runner.py
qcengine/programs/nwchem/harvester.py
qcengine/programs/nwchem/keywords.py
qcengine/programs/nwchem/runner.py
qcengine/programs/psi4.py
qcengine/programs/tests/standard_suite_contracts.py
qcengine/programs/tests/standard_suite_ref.py
qcengine/programs/tests/standard_suite_runner.py
qcengine/programs/tests/test_ghost.py
qcengine/programs/util/__init__.py
qcengine/programs/util/ao_reordering.py
setup.py

Dev snapshot for qcdb testing. Ok to merge except there's other PRs ahead and needs MolSSI/QCElemental#276

ghost handling

---

qcengine/programs/nwchem/runner.py
qcengine/tests/test_procedures.py

Modification of #330 such that you have to deliberately enable NWChem restarts.

nwchem restart opt-in

---

.github/workflows/CI.yml

Update Python version in xtb workflow to 3.10

---

qcengine/procedures/berny.py
qcengine/tests/test_procedures.py

v3 for you! @loriab you can push to this fork.
Closes #300 
Closes #301 
Closes #365

Feature berny handle failed operation v3

---

README.md
docs/source/changelog.rst

WIP: 0.24 changelog

---

qcengine/tests/test_procedures.py

allow torsiondrive test more iterations

---

qcengine/programs/mrchem.py

The harness saves the parallel set up for the MRChem calculation in the `provenance` dictionary. 
- The MRChem harness saves more detailed info about the parallel set up in the `provenance` dictionary of the output.

Save parallel set up for MRChem in provenance

---

qcengine/config.py
qcengine/tests/test_procedures.py

The `jobs_per_node` change was originally proposed in #405 . The larger situation was analyzed in closes #415

change default jobs_per_node and intel cpu_cnt

---

docs/source/changelog.rst
qcengine/programs/gamess/harvester.py

Local testing with a new gamess showed one more little tweak.

gamess and changelog

---

.github/workflows/CI.yml
devtools/conda-envs/mace.yaml
devtools/conda-envs/opt-disp-cf.yaml
devtools/conda-envs/psi-cf.yaml
devtools/conda-envs/psi-nightly.yaml
docs/source/changelog.rst
setup.py

test CI with changelog alone
